[tool.ruff]
# Выбор правил линтинга для проверки
select = ["F", "I"]  # Проверка ошибок и импортов

# Устанавливаем максимальную длину строки
line-length = 90  # Максимальная длина строки



# Для включения Jupyter Notebooks (если нужно)
extend-include = ["*.ipynb"]

# Опционально: использование дополнительных правил для безопасности или улучшения качества кода
# Например, добавить pyupgrade
# extend-select = ["UP", "D"]  # Дополнительные правила

# Исключаем проверку длины строки (если не хотите ее учитывать)
ignore = [
    "E501"  # Отключаем проверку длины строки
]
