"""Fix relationships in models

Revision ID: f315ef91303c
Revises: 3b2d5f15668b
Create Date: 2024-11-08 11:01:17.047858

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f315ef91303c"
down_revision: Union[str, None] = "3b2d5f15668b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tweets_media_id_fkey", "tweets", type_="foreignkey")
    op.drop_column("tweets", "media_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tweets",
        sa.Column("media_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "tweets_media_id_fkey", "tweets", "media", ["media_id"], ["id"]
    )
    # ### end Alembic commands ###
